<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Perfume;
use Illuminate\Database\Seeder;

class PerfumeCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $categoryNames = [
            'Nước hoa nam',
            'Nước hoa nữ',
            'Nước hoa Unisex',
            'Nước hoa Niche',
            'Nước hoa Mini',
            'Giftset nước hoa',
            'Nước hoa Ronaldo',
        ];

        $categories = collect($categoryNames)->mapWithKeys(function (string $name) {
            $category = Category::firstOrCreate(['name' => $name]);

            return [$name => $category];
        });

        $products = [
            [
                'category_id' => $categories['Nước hoa nữ']->id,
                'name' => 'In Love With You Eau de Parfum',
                'slug' => 'in-love-with-you-eau-de-parfum',
                'brand' => 'Emporio Armani',
                'gender' => 'nu',
                'concentration' => 'EDP',
                'volume_ml' => 100,
                'price' => 3250000,
                'sale_price' => 2590000,
                'stock' => 18,
                'stock_10ml' => 45,
                'stock_50ml' => 28,
                'image_url' => 'images/products/amber-glass.jpg',
                'description' => 'Hương trái cây ngọt ngào hòa cùng vanilla ấm áp, nữ tính và cuốn hút.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa nam']->id,
                'name' => 'Stronger With You Intensely',
                'slug' => 'stronger-with-you-intensely',
                'brand' => 'Emporio Armani',
                'gender' => 'nam',
                'concentration' => 'EDP',
                'volume_ml' => 100,
                'price' => 3450000,
                'sale_price' => 2890000,
                'stock' => 14,
                'stock_10ml' => 35,
                'stock_50ml' => 22,
                'image_url' => 'images/products/black-gold.jpg',
                'description' => 'Hương hổ phách, quế và vanilla sâu lắng dành cho phong cách nam tính hiện đại.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa nữ']->id,
                'name' => 'Aqua Allegoria Pera Granita',
                'slug' => 'aqua-allegoria-pera-granita',
                'brand' => 'Guerlain',
                'gender' => 'nu',
                'concentration' => 'EDT',
                'volume_ml' => 75,
                'price' => 3100000,
                'sale_price' => 2690000,
                'stock' => 11,
                'stock_10ml' => 30,
                'stock_50ml' => 18,
                'image_url' => 'images/products/floral-gold.jpg',
                'description' => 'Hương lê tươi mát, bưởi và hoa trắng tạo cảm giác trong trẻo, thanh lịch.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa Niche']->id,
                'name' => 'Royal Oud 1770',
                'slug' => 'royal-oud-1770',
                'brand' => 'Maison Privée',
                'gender' => 'unisex',
                'concentration' => 'Parfum',
                'volume_ml' => 50,
                'price' => 4800000,
                'sale_price' => 3990000,
                'stock' => 8,
                'stock_10ml' => 20,
                'stock_50ml' => 14,
                'image_url' => 'images/products/midnight-hand.jpg',
                'description' => 'Trầm hương, da thuộc và gia vị phương Đông trong một cấu trúc hương sang trọng.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa Ronaldo']->id,
                'name' => 'Nước Hoa Cristiano Ronaldo CR7 EDT 100ml Chính Hãng',
                'slug' => 'nuoc-hoa-cristiano-ronaldo-cr7-edt-100ml-chinh-hang',
                'brand' => 'Cristiano Ronaldo',
                'gender' => 'nam',
                'concentration' => 'EDT',
                'volume_ml' => 100,
                'price' => 980000,
                'sale_price' => 100000,
                'stock' => 6,
                'stock_10ml' => 15,
                'stock_50ml' => 9,
                'image_url' => 'https://yperfume.net/wp-content/uploads/2023/05/Nuoc-Hoa-Cristiano-Ronaldo-CR7-Y-Perfume.jpg',
                'description' => 'Nước hoa Cristiano Ronaldo CR7 là một dòng nước hoa nam tính và quyến rũ, mang đậm chất cá nhân của Cristiano Ronaldo – một trong những cầu thủ bóng đá hàng đầu thế giới.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa Ronaldo']->id,
                'name' => 'Nước Hoa Cristiano Ronaldo CR7',
                'slug' => 'nuoc-hoa-cristiano-ronaldo-cr7',
                'brand' => 'ronaldo',
                'gender' => 'nam',
                'concentration' => 'EDP',
                'volume_ml' => 200,
                'price' => 1500000,
                'sale_price' => null,
                'stock' => 11,
                'stock_10ml' => 28,
                'stock_50ml' => 17,
                'image_url' => 'images/products/009c9a68-94ba-445d-a589-d9842b9f3b09.jpg',
                'description' => 'Review nước hoa Cr7 – Hương thơm đẳng cấp, cuốn hút dành cho phái mạnh',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa nữ']->id,
                'name' => 'Miss Dior Blooming Bouquet EDT',
                'slug' => 'miss-dior-blooming-bouquet',
                'brand' => 'Dior',
                'gender' => 'nu',
                'concentration' => 'Eau de Toilette',
                'volume_ml' => 100,
                'price' => 3850000,
                'sale_price' => 3390000,
                'stock' => 15,
                'stock_10ml' => 38,
                'stock_50ml' => 23,
                'image_url' => 'images/products/miss-dior-blooming.jpg',
                'description' => 'Miss Dior Blooming Bouquet là tuyệt tác nước hoa với sắc hồng dịu dàng, tựa như một bó hoa tươi thắm gồm hoa mẫu đơn và hoa hồng Damask mơn man, điểm xuyết xạ hương trắng tinh tế.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa nữ']->id,
                'name' => 'Chanel Chance Eau Tendre EDP',
                'slug' => 'chanel-chance-eau-tendre',
                'brand' => 'Chanel',
                'gender' => 'nu',
                'concentration' => 'Eau de Parfum',
                'volume_ml' => 100,
                'price' => 4200000,
                'sale_price' => 3750000,
                'stock' => 12,
                'stock_10ml' => 30,
                'stock_50ml' => 18,
                'image_url' => 'images/products/chanel-chance-tendre.jpg',
                'description' => 'Chanel Chance Eau Tendre mang sắc hồng phấn thơ mộng, là sự hòa quyện nồng nàn giữa hương hoa bưởi, mộc qua thanh khiết cùng hoa nhài và xạ hương trắng đầy nữ tính và kiêu kỳ.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa Niche']->id,
                'name' => 'Parfums de Marly Delina Exclusif',
                'slug' => 'parfums-de-marly-delina-exclusif',
                'brand' => 'Parfums de Marly',
                'gender' => 'nu',
                'concentration' => 'Parfum Extrait',
                'volume_ml' => 75,
                'price' => 7200000,
                'sale_price' => 6490000,
                'stock' => 8,
                'stock_10ml' => 20,
                'stock_50ml' => 12,
                'image_url' => 'images/products/delina-exclusif.jpg',
                'description' => 'Được xưng tụng là "Tiểu thư hoàng gia Pháp", Delina Exclusif trong thiết kế chai hồng pastel quý tộc đính tua rua lụa, mở ra hương hoa hồng Thổ Nhĩ Kỳ, vải thiều ngọt ngào, trầm hương và hổ phách sang trọng tột bậc.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa Unisex']->id,
                'name' => 'Tom Ford Rose Prick Private Blend',
                'slug' => 'tom-ford-rose-prick-edp',
                'brand' => 'Tom Ford',
                'gender' => 'unisex',
                'concentration' => 'Eau de Parfum',
                'volume_ml' => 50,
                'price' => 8500000,
                'sale_price' => 7690000,
                'stock' => 6,
                'stock_10ml' => 15,
                'stock_50ml' => 9,
                'image_url' => 'images/products/tom-ford-rose-prick.jpg',
                'description' => 'Thuộc bộ sưu tập Private Blend xa xỉ, Rose Prick sở hữu thiết kế chai hồng phấn nhám mờ kiêu hãnh. Hương thơm hòa quyện giữa hoa hồng tháng Năm, hoa hồng Bulgari cùng tiêu cay Tứ Xuyên và hoắc hương gai góc đầy lôi cuốn.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa nữ']->id,
                'name' => 'Narciso Rodriguez Musc Noir Rose',
                'slug' => 'narciso-rodriguez-musc-noir-rose',
                'brand' => 'Narciso Rodriguez',
                'gender' => 'nu',
                'concentration' => 'Eau de Parfum',
                'volume_ml' => 100,
                'price' => 3450000,
                'sale_price' => 2950000,
                'stock' => 20,
                'stock_10ml' => 50,
                'stock_50ml' => 30,
                'image_url' => 'images/products/narciso-musc-noir-rose.jpg',
                'description' => 'Vẻ đẹp gợi cảm ma mị trong thân chai thủy tinh phớt hồng khói trong suốt. Nốt hương nồng say của quả mận mọng nước, hoa huệ tây quyến rũ và nốt xạ hương độc quyền khó cưỡng.',
                'is_active' => true,
            ],
            [
                'category_id' => $categories['Nước hoa nam']->id,
                'name' => 'Dior Sauvage',
                'slug' => 'dior-sauvage',
                'brand' => 'Dior',
                'gender' => 'nam',
                'concentration' => 'EDP',
                'volume_ml' => 100,
                'price' => 3780000,
                'sale_price' => null,
                'stock' => 16,
                'stock_10ml' => 40,
                'stock_50ml' => 24,
                'image_url' => 'https://orchard.vn/wp-content/uploads/2018/04/dior-sauvage-edp_3.jpg',
                'description' => 'Hương thơm nam tính và ấm áp, lý tưởng cho những buổi tối lãng mạn.',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Perfume::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
