@extends('layouts.store')

@section('title', 'Hộp Thử Mùi Tự Chọn (Discovery Box) · Trải Nghiệm 3-5 Mẫu Chiết | Ha Thu Perfume')
@section('meta_description', 'Tự tay tuyển chọn 3 đến 5 ống chiết nước hoa chính hãng cao cấp trước khi mua fullbox. Tặng kèm voucher hoàn tiền 100K.')

@section('content')
<div class="store-container ht-discovery-page">
    <header class="ht-discovery-hero">
        <span class="ht-badge-pill">🎁 BỘ SƯU TẬP TRẢI NGHIỆM</span>
        <h1 class="ht-discovery-title">Tự Thiết Kế <em>Hộp Thử Mùi</em> Của Riêng Bạn</h1>
        <p class="ht-discovery-subtitle">Đừng vội mua chai lớn khi chưa thử lên da! Hãy chọn 3 hoặc 5 ống chiết cao cấp (2ml - 5ml) để trải nghiệm trọn vẹn cả ngày dài. Tặng ngay voucher hoàn tiền khi mua fullsize.</p>
    </header>

    {{-- Package Switcher --}}
    <div class="ht-box-size-switcher">
        <button type="button" class="size-btn active" data-size="3" data-price="199000">
            <strong>Hộp 3 Mẫu Chiết</strong>
            <span>199.000₫ · Tặng voucher 50K</span>
        </button>
        <button type="button" class="size-btn" data-size="5" data-price="299000">
            <span class="hot-tag">TIẾT KIỆM NHẤT</span>
            <strong>Hộp 5 Mẫu Chiết</strong>
            <span>299.000₫ · Tặng voucher 100K</span>
        </button>
    </div>

    {{-- 3D Virtual Gift Box Preview --}}
    <div class="ht-virtual-box">
        <div class="box-lid-label">
            <span>HA THU PERFUME STUDIO · DISCOVERY BOX</span>
        </div>
        <div class="box-slots-wrap" id="boxSlots">
            {{-- 3 or 5 slots generated by JS --}}
        </div>
        <div class="box-summary-bar">
            <div class="box-price-info">
                <span class="label">Tổng giá trị Hộp Thử Mùi:</span>
                <span class="price" id="boxPriceDisplay">199.000₫</span>
                <span class="extra-benefit">✓ Đóng hộp nhung quà tặng · Đính kèm bảng ghi chú tầng hương</span>
            </div>
            <form action="{{ route('cart.add-discovery-box') }}" method="POST" id="discoveryForm">
                @csrf
                <input type="hidden" name="size" id="inputBoxSize" value="3">
                <div id="hiddenInputsWrap"></div>
                <button type="submit" class="ht-button ht-button-primary" id="addBoxBtn" disabled>
                    Vui lòng chọn đủ 3 mẫu để thêm vào giỏ
                </button>
            </form>
        </div>
    </div>

    {{-- Perfume Picker Catalog --}}
    <section class="ht-perfume-picker-section">
        <div class="picker-header">
            <div>
                <h2>Chọn Mùi Hương Cho Từng Ống Chiết</h2>
                <p>Bấm nút <strong>"+ Cho vào hộp"</strong> trên từng chai để lấp đầy các khay mẫu thử.</p>
            </div>
            <div class="picker-filter">
                <button class="filter-tab active" data-filter="all">Tất Cả</button>
                <button class="filter-tab" data-filter="nu">Nữ Tính</button>
                <button class="filter-tab" data-filter="nam">Nam Tính</button>
                <button class="filter-tab" data-filter="unisex">Unisex</button>
            </div>
        </div>

        <div class="picker-grid" id="pickerGrid">
            @foreach($perfumes as $perfume)
            <div class="picker-card" data-gender="{{ $perfume->gender }}" data-id="{{ $perfume->id }}" data-name="{{ $perfume->name }}" data-brand="{{ $perfume->brand }}" data-img="{{ $perfume->image_src ?: asset('images/perfume-default.jpg') }}">
                <div class="card-thumb">
                    <img src="{{ $perfume->image_src ?: asset('images/perfume-default.jpg') }}" alt="{{ $perfume->name }}" loading="lazy">
                </div>
                <div class="card-details">
                    <span class="card-brand">{{ $perfume->brand }}</span>
                    <h3 class="card-name">{{ $perfume->name }}</h3>
                    <p class="card-family">{{ $perfume->category->name ?? 'Nước hoa' }} · {{ ucfirst($perfume->gender) }}</p>
                    <p class="card-note">🌸 {{ Str::limit($perfume->scent_profile['top']['notes'] ?? 'Tươi mát, thanh lịch', 45) }}</p>
                </div>
                <button type="button" class="ht-button ht-button-light select-sample-btn" data-id="{{ $perfume->id }}">
                    + Cho vào hộp
                </button>
            </div>
            @endforeach
        </div>
    </section>
</div>

<style>
.ht-discovery-page {
    padding: 40px 20px 80px;
    max-width: 1100px;
    margin: 0 auto;
}
.ht-discovery-hero {
    text-align: center;
    margin-bottom: 30px;
}
.ht-discovery-title {
    font: 400 clamp(28px, 5vw, 42px) 'Playfair Display', Georgia, serif;
    color: #2b1f26;
    margin: 12px 0 10px;
}
.ht-discovery-title em {
    color: #c2476a;
    font-style: italic;
}
.ht-discovery-subtitle {
    color: #6d5b64;
    font-size: 16px;
    max-width: 720px;
    margin: 0 auto;
    line-height: 1.6;
}
.ht-box-size-switcher {
    display: flex;
    justify-content: center;
    gap: 16px;
    margin-bottom: 30px;
    flex-wrap: wrap;
}
.size-btn {
    border: 2px solid #f3d4e0;
    border-radius: 18px;
    padding: 18px 28px;
    background: #ffffff;
    cursor: pointer;
    text-align: center;
    min-width: 240px;
    position: relative;
    transition: all 0.25s ease;
}
.size-btn strong {
    display: block;
    font-size: 18px;
    color: #3b2832;
    margin-bottom: 4px;
}
.size-btn span {
    font-size: 13.5px;
    color: #8b6b7a;
}
.size-btn.active {
    border-color: #c2476a;
    background: #fff0f5;
    box-shadow: 0 10px 28px rgba(194, 71, 106, 0.18);
    transform: translateY(-2px);
}
.size-btn .hot-tag {
    position: absolute;
    top: -10px;
    right: 16px;
    background: #c2476a;
    color: #fff;
    font-size: 10px;
    font-weight: 700;
    padding: 3px 8px;
    border-radius: 10px;
}

/* Virtual Gift Box */
.ht-virtual-box {
    background: linear-gradient(135deg, #2b1b22, #4a2836);
    border-radius: 28px;
    padding: 32px 30px;
    color: #fff;
    box-shadow: 0 20px 50px rgba(74, 40, 54, 0.35);
    margin-bottom: 50px;
    border: 2px solid #87435f;
}
.box-lid-label {
    text-align: center;
    letter-spacing: 3px;
    font-size: 12px;
    color: #fbcfe8;
    margin-bottom: 24px;
    border-bottom: 1px dashed rgba(251, 207, 232, 0.2);
    padding-bottom: 12px;
}
.box-slots-wrap {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(170px, 1fr));
    gap: 16px;
    margin-bottom: 28px;
}
.box-slot {
    background: rgba(255, 255, 255, 0.08);
    border: 2px dashed rgba(251, 207, 232, 0.4);
    border-radius: 18px;
    padding: 20px 14px;
    text-align: center;
    min-height: 200px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    position: relative;
    transition: all 0.25s ease;
}
.box-slot.filled {
    background: rgba(255, 255, 255, 0.16);
    border: 2px solid #f472b6;
    box-shadow: 0 8px 24px rgba(244, 114, 182, 0.25);
}
.slot-vial-icon {
    font-size: 40px;
    margin-bottom: 10px;
    opacity: 0.5;
}
.slot-filled-img {
    width: 64px;
    height: 64px;
    object-fit: contain;
    margin-bottom: 10px;
}
.slot-brand {
    font-size: 10.5px;
    letter-spacing: 1px;
    color: #fbcfe8;
    text-transform: uppercase;
}
.slot-name {
    font-size: 13.5px;
    font-weight: 600;
    color: #fff;
    margin: 3px 0 10px;
    line-height: 1.25;
}
.remove-sample-btn {
    background: rgba(239, 68, 68, 0.2);
    border: 1px solid rgba(239, 68, 68, 0.5);
    color: #fca5a5;
    border-radius: 8px;
    padding: 3px 8px;
    font-size: 11px;
    cursor: pointer;
    transition: background 0.2s;
}
.remove-sample-btn:hover {
    background: rgba(239, 68, 68, 0.4);
    color: #fff;
}
.slot-empty-text {
    font-size: 13px;
    color: #e5b3c8;
}
.slot-empty-num {
    font-size: 11px;
    color: #a87990;
    margin-top: 4px;
}
.box-summary-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top: 1px solid rgba(255, 255, 255, 0.15);
    padding-top: 20px;
    flex-wrap: wrap;
    gap: 16px;
}
.box-price-info .label {
    display: block;
    font-size: 13px;
    color: #fbcfe8;
}
.box-price-info .price {
    font-size: 28px;
    font-weight: 700;
    color: #fef08a;
    display: block;
}
.box-price-info .extra-benefit {
    font-size: 12px;
    color: #cbd5e1;
    display: block;
    margin-top: 3px;
}

/* Picker Catalog */
.ht-perfume-picker-section {
    margin-top: 20px;
}
.picker-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    margin-bottom: 24px;
    flex-wrap: wrap;
    gap: 16px;
}
.picker-header h2 {
    font: 600 24px Georgia, serif;
    color: #2b1f26;
    margin: 0 0 6px;
}
.picker-header p {
    color: #715865;
    font-size: 14px;
    margin: 0;
}
.picker-filter {
    display: flex;
    gap: 8px;
}
.filter-tab {
    border: 1px solid #e5d3dc;
    background: #fff;
    color: #55444e;
    padding: 6px 14px;
    border-radius: 20px;
    font-size: 13px;
    cursor: pointer;
    transition: all 0.2s;
}
.filter-tab.active {
    background: #c2476a;
    border-color: #c2476a;
    color: #fff;
}
.picker-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
    gap: 20px;
}
.picker-card {
    background: #fff;
    border: 1px solid #fce7f3;
    border-radius: 18px;
    padding: 18px;
    display: flex;
    flex-direction: column;
    box-shadow: 0 4px 16px rgba(0,0,0,0.03);
    transition: transform 0.2s, box-shadow 0.2s;
}
.picker-card:hover {
    transform: translateY(-3px);
    box-shadow: 0 10px 24px rgba(194, 71, 106, 0.1);
}
.card-thumb {
    text-align: center;
    background: #faf4f7;
    border-radius: 12px;
    padding: 12px;
    margin-bottom: 12px;
}
.card-thumb img {
    height: 110px;
    object-fit: contain;
}
.card-brand {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: #c2476a;
    font-weight: 700;
}
.card-name {
    font: 600 16px Georgia, serif;
    color: #2b1f26;
    margin: 3px 0 4px;
}
.card-family {
    font-size: 12px;
    color: #8b7782;
    margin-bottom: 6px;
}
.card-note {
    font-size: 12px;
    color: #5e4b56;
    line-height: 1.4;
    margin-bottom: 14px;
    flex-grow: 1;
}
.select-sample-btn {
    width: 100%;
    font-weight: 600;
    text-align: center;
}
.select-sample-btn.selected {
    background: #2e7d32;
    color: #fff;
    border-color: #2e7d32;
}
</style>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {
    let currentSize = 3;
    let selectedSamples = []; // array of objects {id, name, brand, img}
    const sizeBtns = document.querySelectorAll('.size-btn');
    const boxSlots = document.getElementById('boxSlots');
    const priceDisplay = document.getElementById('boxPriceDisplay');
    const addBoxBtn = document.getElementById('addBoxBtn');
    const inputBoxSize = document.getElementById('inputBoxSize');
    const hiddenInputsWrap = document.getElementById('hiddenInputsWrap');

    function renderBox() {
        boxSlots.innerHTML = '';
        for (let i = 0; i < currentSize; i++) {
            const sample = selectedSamples[i];
            const slot = document.createElement('div');
            slot.className = 'box-slot' + (sample ? ' filled' : '');

            if (sample) {
                slot.innerHTML = `
                    <img src="${sample.img}" alt="${sample.name}" class="slot-filled-img">
                    <span class="slot-brand">${sample.brand}</span>
                    <strong class="slot-name">${sample.name}</strong>
                    <button type="button" class="remove-sample-btn" data-index="${i}">✕ Đổi mùi khác</button>
                `;
            } else {
                slot.innerHTML = `
                    <div class="slot-vial-icon">🧪</div>
                    <span class="slot-empty-text">+ Chọn mẫu ${i + 1}</span>
                    <span class="slot-empty-num">Khe thử mùi số ${i + 1}</span>
                `;
            }
            boxSlots.appendChild(slot);
        }

        // Update hidden inputs for form
        hiddenInputsWrap.innerHTML = '';
        selectedSamples.forEach(s => {
            const inp = document.createElement('input');
            inp.type = 'hidden';
            inp.name = 'perfume_ids[]';
            inp.value = s.id;
            hiddenInputsWrap.appendChild(inp);
        });

        // Update add to cart button
        if (selectedSamples.length === currentSize) {
            addBoxBtn.disabled = false;
            addBoxBtn.textContent = `Thêm Hộp ${currentSize} Mẫu Vào Giỏ Hàng (${currentSize === 5 ? '299.000₫' : '199.000₫'})`;
        } else {
            addBoxBtn.disabled = true;
            addBoxBtn.textContent = `Vui lòng chọn thêm ${currentSize - selectedSamples.length} mẫu nữa`;
        }

        // Highlight selected buttons in picker
        document.querySelectorAll('.select-sample-btn').forEach(b => {
            const id = parseInt(b.dataset.id);
            const isSel = selectedSamples.some(s => s.id === id);
            b.classList.toggle('selected', isSel);
            b.textContent = isSel ? '✓ Đã chọn vào hộp' : '+ Cho vào hộp';
        });
    }

    sizeBtns.forEach(btn => {
        btn.addEventListener('click', function () {
            sizeBtns.forEach(b => b.classList.remove('active'));
            this.classList.add('active');
            currentSize = parseInt(this.dataset.size);
            priceDisplay.textContent = parseInt(this.dataset.price).toLocaleString('vi-VN') + '₫';
            inputBoxSize.value = currentSize;
            if (selectedSamples.length > currentSize) {
                selectedSamples = selectedSamples.slice(0, currentSize);
            }
            renderBox();
        });
    });

    // Handle selecting perfume from catalog
    document.querySelectorAll('.select-sample-btn').forEach(btn => {
        btn.addEventListener('click', function () {
            const card = this.closest('.picker-card');
            const id = parseInt(card.dataset.id);
            const name = card.dataset.name;
            const brand = card.dataset.brand;
            const img = card.dataset.img;

            const existingIdx = selectedSamples.findIndex(s => s.id === id);
            if (existingIdx !== -1) {
                selectedSamples.splice(existingIdx, 1);
            } else {
                if (selectedSamples.length >= currentSize) {
                    alert(`Hộp hiện tại chứa tối đa ${currentSize} mẫu. Bạn hãy đổi một mẫu khác hoặc chọn gói Hộp 5 mẫu nhé!`);
                    return;
                }
                selectedSamples.push({ id, name, brand, img });
            }
            renderBox();
        });
    });

    // Handle removing sample from slot
    boxSlots.addEventListener('click', function (e) {
        if (e.target.classList.contains('remove-sample-btn')) {
            const idx = parseInt(e.target.dataset.index);
            selectedSamples.splice(idx, 1);
            renderBox();
        }
    });

    // Filter tabs
    document.querySelectorAll('.filter-tab').forEach(tab => {
        tab.addEventListener('click', function () {
            document.querySelectorAll('.filter-tab').forEach(t => t.classList.remove('active'));
            this.classList.add('active');
            const filter = this.dataset.filter;
            document.querySelectorAll('.picker-card').forEach(card => {
                if (filter === 'all' || card.dataset.gender === filter) {
                    card.style.display = 'flex';
                } else {
                    card.style.display = 'none';
                }
            });
        });
    });

    renderBox();
});
</script>
@endpush
@endsection
